name: Deploy to GitHub Pages

on:
  # Se ejecuta al hacer push a la rama main
  push:
    branches: [ main ]
  # Se puede ejecutar manualmente
  workflow_dispatch:

# Permisos para desplegar en GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build Astro site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install, build, and upload your site
        uses: withastro/action@v3
        # Puedes configurar esto si usas otro node o gestor
        # with:
        #   node-version: 20
        #   package-manager: pnpm@latest
        #   path: .

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
